const AUTH_START = "AUTH_START";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_ERROR = "AUTH_ERROR";
const SET_USERNAME = "SET_USERNAME";
const LOGOUT_USER = "LOGOUT_USER";

const SILOS_LOAD_START = "SILOS_LOAD_START";
const SILOS_LOAD_SUCCESS = "SILOS_LOAD_SUCCESS";
const SILOS_LOAD_ERROR = "SILOS_LOAD_ERROR";

export {
  AUTH_START,
  AUTH_SUCCESS,
  AUTH_ERROR,
  SET_USERNAME,
  LOGOUT_USER,
  SILOS_LOAD_START,
  SILOS_LOAD_SUCCESS,
  SILOS_LOAD_ERROR,
};
