const AUTH_START = "AUTH_START";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_ERROR = "AUTH_ERROR";
const SET_USERNAME = "SET_USERNAME";
const LOGOUT_USER = "LOGOUT_USER";

const SILOS_LOAD_START = "SILOS_LOAD_START";
const SILOS_LOAD_SUCCESS = "SILOS_LOAD_SUCCESS";
const SILOS_LOAD_ERROR = "SILOS_LOAD_ERROR";

const NOTIFICATIONS_LOAD_START = "NOTIFICATIONS_LOAD_START";
const NOTIFICATIONS_LOAD_ERROR = "NOTIFICATIONS_LOAD_ERROR";
const NOTIFICATIONS_LOAD_SUCCESS = "NOTIFICATIONS_LOAD_SUCCESS";

const MEASUREMENT_LOAD_START = "MEASUREMENT_LOAD_START"
const MEASUREMENT_LOAD_ERROR = "MEASUREMENT_LOAD_ERROR"
const MEASUREMENT_LOAD_SUCCESS = "MEASUREMENT_LOAD_SUCCESS"

export {
  AUTH_START,
  AUTH_SUCCESS,
  AUTH_ERROR,
  SET_USERNAME,
  LOGOUT_USER,
  SILOS_LOAD_START,
  SILOS_LOAD_SUCCESS,
  SILOS_LOAD_ERROR,
  NOTIFICATIONS_LOAD_START,
  NOTIFICATIONS_LOAD_ERROR,
  NOTIFICATIONS_LOAD_SUCCESS,
  MEASUREMENT_LOAD_START,
  MEASUREMENT_LOAD_ERROR,
  MEASUREMENT_LOAD_SUCCESS,
}
